[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true


# Colors (Gruvbox Material Hard Dark)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
family = "Sauce Code Pro Nerd Font"
style = "Medium"

[font.italic]
family = "Sauce Code Pro Nerd Font"
style = "Light Italic"

[font.normal]
family = "SauceCodePro NFM"
style = "SemiBold"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
{action = "SpawnNewInstance", key = "Return", mods = "Super|Shift"},
{key = "F", mods = "Control", chars = "tmux-sessionizer\r"},
]

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# [background]
# opacity = 0.0

[window]
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
