[[themes]]
name = "base16"
[themes.palette]
background = "#333333"
foreground = "#CCCCCC"
black = "#333333"
red = "#CCCCCC"
green = "#CCCCCC"
yellow = "#CCCCCC"
blue = "#CCCCCC"
magenta = "#CCCCCC"
cyan = "#CCCCCC"
white = "#CCCCCC"
bright_black = "#CCCCCC"
bright_red = "#CCCCCC"
bright_green = "#CCCCCC"
bright_yellow = "#CCCCCC"
bright_blue = "#CCCCCC"
bright_magenta = "#CCCCCC"
bright_cyan = "#CCCCCC"
bright_white = "#CCCCCC"
