$image = /home/seger/.dotfiles/scripts/.config/scripts/theme-switcher/backgrounds/atelier-*-light/DSCF1532.JPG

$base00 = rgba(f4f3ecff)
$base01 = rgba(e7e6dfff)
$base02 = rgba(929181ff)
$base03 = rgba(878573ff)
$base04 = rgba(6c6b5aff)
$base05 = rgba(5f5e4eff)
$base06 = rgba(302f27ff)
$base07 = rgba(22221bff)
$base08 = rgba(ba6236ff)
$base09 = rgba(ae7313ff)
$base0A = rgba(a5980dff)
$base0B = rgba(7d9726ff)
$base0C = rgba(5b9d48ff)
$base0D = rgba(36a166ff)
$base0E = rgba(5f9182ff)
$base0F = rgba(9d6c7cff)
