general {
    lock_cmd = pidof hyprlock || hyprlock
}

# Dim after 5 minutes
listener {
    timeout = 180
    on-timeout = sh -lc 'brightnessctl -s set 20%'
    on-resume  = sh -lc 'brightnessctl -r'
}

# Lock after 60 minutes (your existing)
listener {
    timeout = 360
    on-timeout = loginctl lock-session
}
