general {
    lock_cmd = pidof hyprlock || hyprlock
}

# Dim after 5 minutes
listener {
    timeout = 300
    on-timeout = sh -lc 'brightnessctl -s set 20%'
    on-resume  = sh -lc 'brightnessctl -r'
}

# Lock after 15 minutes
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}
