# Base16 Colors for tmux

set -g status-bg                          "#f4f3ec"
set -gq @thm_bar_bg                       "#f4f3ec"

set -gq @thm_bg                           "#f4f3ec"
set -gq @thm_fg                           "#5f5e4e"
set -gq @thm_primary                      "#36a166"
set -gq @thm_secondary                    "#5f9182"
set -gq @thm_surface_low                  "#e7e6df"
set -gq @thm_surface                      "#f4f3ec"
set -gq @thm_surface_variant              "#878573"
set -gq @thm_outline                      "#878573"
set -gq @thm_text_variant                 "#6c6b5a"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
