# Base16 Colors for tmux

set -g status-bg                          "#333333"
set -gq @thm_bar_bg                       "#333333"

set -gq @thm_bg                           "#333333"
set -gq @thm_fg                           "#CCCCCC"
set -gq @thm_primary                      "#CCCCCC"
set -gq @thm_secondary                    "#CCCCCC"
set -gq @thm_surface_low                  "#333333"
set -gq @thm_surface                      "#333333"
set -gq @thm_surface_variant              "#CCCCCC"
set -gq @thm_outline                      "#CCCCCC"
set -gq @thm_text_variant                 "#CCCCCC"

set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"
