#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 [on|off]"
    exit 1
fi

case "$1" in
    on)
        echo 2 | sudo tee /sys/class/leds/*/brightness
        ;;
    off)
        echo 0 | sudo tee /sys/class/leds/*/brightness
        ;;
    *)
        echo "Invalid argument: $1"
        echo "Usage: $0 [on|off]"
        exit 1
        ;;
esac
