#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$( (find ~/projects ~/personal -mindepth 0 -maxdepth 1 -type d; echo ~/.dotfiles) | fzf)
    # selected=$(find ~/projects ~/personal -mindepth 0 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "Starting tmux"
    tmux new-session -s $selected_name -c $selected
    # # Check if the session already exists
    # tmux has-session -t "$SESSION" 2>/dev/null
    # Create a new detached session with the first window named 'editor'
    # start the window with vim
    #
    # set the session name
    SESSION=$selected_name

    tmux new-window -t "$SESSION:1" -n nvim -c $SESSION remain-on-exit "nvim ."

    tmux new-window -t "$SESSION:2" -n run -c $SESSION

    tmux new-window -t "$SESSION:3" -n shell -c $SESSION
 
    tmux select-window -t "$SESSION:1"

    # Attach to the session
    tmux attach-session -t "$SESSION"
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    echo "Creating new session"
    tmux new-session -ds $selected_name -c $selected -n editor "nvim .; zsh"
    # set the session name
    SESSION=$selected_name

    tmux new-window -t "$SESSION:2" -n run -c $selected

    tmux new-window -t "$SESSION:3" -n shell -c $selected

    tmux select-window -t "$SESSION:1"

    # Attach to the session
    tmux attach-session -t "$SESSION"
fi

tmux switch-client -t $selected_name
